name: Project Publishing
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths: [ 'AvaloniaIDE/**', '**/Publish.yml' ]
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            runtime: win-x64
          - platform: windows-latest
            runtime: win-arm64
          - platform: macos-latest
            runtime: osx-x64
          - platform: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-cache-${{ matrix.runtime }}
      - run: dotnet publish -r ${{ matrix.runtime }}
      - uses: actions/upload-artifact@v5
        with:
          name: Release-${{ matrix.runtime }}
          path: |
            **/publish
            !**/*.pdb
            !**/*.dbg
            !**/*.dSYM
